### ISSUE TITLE
ECP-1 : Distribution of Development Funds

### ISSUE THREAD

**Issue by pistol22cal** [Ether1Project/ECPs#11]
ECP-1: Distribution of Development Funds
ECP Discussion End: 04 Feb 2020 0:00 UTC
ECP Vote Date Start | End: 05 Feb 2020 0:01 UTC to 06 Feb 2020 0:01 UTC

ECP Originator: Provisional Council
ECP Sponsor: Provisional Council
ECP Motivation: Pay the Bills
ECP Summary: How to spend Dev Funds

Details

-PROVISIONAL BUDGET – REVIST IN 60 DAYS – IF THIS BUDGET WORKS WE VOTE TO MAKE IT PERMANENT FOR THIS COUNCIL.

-Total Budget $ETHO - 172,800.00 Per 30 Days

-This ECP to be activated 15 Feb 2020

-Allocation of Funds

·        Council Fund - 100% of Dev Fund goes to this wallet.*

*Funds are to be spent on Approved ECP's only.

**Costs are to be paid via single ongoing ECP updated each month, this ECP has Pre-Approval to avoid costs not being paid. Costs are to communicated to the council no later than the last day of the month. Funds shall be sent to Dev-James no later than 3 days after council knows the amount needed.

Anyone who needs funding must create an ECP for that funding to be covered. Standard 4 to 7 vote needed for approval. ECP's can be vetoed by Dev-James and a veto can be overruled by a 6/7 vote from the council.

Section 2.  Creation 
--- CableGod to create 1 smart contract / multisig wallet for the council 4 out of 7 votes needed to send funds ---

1.   Council Fund

Section 3. Execution 

Dev-James - Project founder of Ether-1 - Is to distribute funds every 30 day period starting, as outlined in this ECP if approved via 4/7 vote by Provisional Council  - 15 Feb 2020 

ALL WALLETS THAT COLLECT ANY FUNDS FROM THE DEVELOPMENT FEE SHALL BE PUBLICLY KNOWN.

**Comment by pistol22cal** [comment]
This is passed and is being closed

**Comment by Goose-Tech** [comment]
I voted on it to make it unanimous! :-p

**Comment by Primate411** [comment]
@qbvbsite aka (@CableGod | Ether-1#8247) volunteered to explore the multisig council wallet possibilities for the council to consider and test.
