### ISSUE TITLE
ECP-2 Council should have Moderator Powers on Ether-1 Discord

### ISSUE THREAD

**Issue by pistol22cal** [Ether1Project/ECPs#12]
ECP-2: Council should have Moderator Powers on Ether-1 Discord
ECP Discussion End: 05 Feb 2020 0:00 UTC
ECP Vote Date Start | End: 06 Feb 2020 0:01 UTC to 07 Feb 2020 0:01 UTC

ECP Originator: Pistol22Cal
ECP Sponsor: Pistol22Cal
ECP Motivation: Give Council Moderator Powers in order to work within chat channels more easily.
ECP Summary: Council Members should have moderator powers 

Details

Council members should have moderator powers. Further experienced Council should have rights to create and manage channels in Ether-1 discord. Council members that have higher than moderator powers should be discussed and voted on within the council.

**Comment by Bigpiggy01** [comment]
Looks good to me!

**Comment by Primate411** [comment]
I agree.  What kind of moderator powers did you have in mind? kick/ban/modify messages (delete messages)/create channels... anything else?

**Comment by Primate411** [comment]
Ether Discord is here: https://discord.gg/MFn9Tmz

**Comment by pistol22cal** [comment]
> I agree. What kind of moderator powers did you have in mind? kick/ban/modify messages (delete messages)/create channels... anything else?

Just mod powers - no typo slow mo - able to delete messages - able to pin - you know standard mod stuff --- I think you should keep the ability to admin the discord since you have a ton of experience.

**Comment by Primate411** [comment]
@dylie has verbally confirmed he agrees with this proposal.  Moving to close and implement as there are also no objections from @Dev-JamesR
