### ISSUE TITLE
Council Wallets

### ISSUE THREAD

**Issue by pistol22cal** [Ether1Project/ECPs#17]
PLEASE ALL COUNCIL MEMBERS LIST A WALLET YOU WANT TO USE FOR COUNCIL BUSINESS.

THIS IS ALSO THE WALLET WE WILL USE FOR THE MULTISIG WALLET.

Pistol:  `0x31e2d1e5711f90e549b6809bDCedB44af8854B2b`

**Comment by qbvbsite** [comment]
CableGod: 0xFA70838b64B8146F3e970EF9Bc8177a567518477

**Comment by Goose-Tech** [comment]
Goose: 0x52DD7D3952be4240228B0Ad2C77aE124De42C386

**Comment by Primate411** [comment]
Primate:
0x0F12288bD92248d02EeaC5E9fc22d25Cd64a735B

**Comment by Bigpiggy01** [comment]
0x64260353e717D213Da1425670a890f22fa41f86B

**Comment by dylie** [comment]
0xE2210f2fEf4eb8b02f0D4EC816c2a9040975D390

**Comment by hashratez** [comment]
0x2812BE8E42BFC059D0e461A9cDf19b2a329cc85E

**Comment by dylie** [comment]
Hello guys, the council multisig wallet is live and ready for your use over at https://decentralizedhosting.online/ Please follow these steps to add the multisig contract to your dashboard:

NOTE: This requires ethomask/metamask to work. @ETHER-1 COUNCIL please use the address provided in ecp https://github.com/Ether1Project/ECPs/issues/17. "Terms of use" Just click read and accept and continue. -> "Wallets" click ADD http://prntscr.com/r0ynot -> Select "Restore deployed wallet" and click next http://prntscr.com/r0yoy9 Fill in a name, for example "ether-1 council sig wallet" + address **0xBA57dFe21F78F921F53B83fFE1958Bbab50F6b46** and click "OK". 


THAT'S IT CONGRATZ! 

-Dylie

**Comment by Primate411** [comment]
Thanks @dylie for deploying the multisig wallet!

It's since been moved to https://fund.ether1.org 

Tracking spreadsheet here: https://docs.google.com/spreadsheets/d/1xG7OA8ICmJwkWlNhGiQD9dOvfs2jvvQ3QY_UiauOevs/edit?usp=sharing

**Comment by Bigpiggy01** [comment]
And I had to try using UFC files on a twice encrypted drive so we're replacing mine:

0xC068Ebbc1D8a307a7dA4Bd0767C9e7fd34122B1C

**Comment by Primate411** [comment]
Reopening this issue to document @Crypto-Saiyan wallet

**Comment by Crypto-Saiyan** [comment]
0xE1Fe94c4B9B697Fe773534A79A301FA4f186e5Ff
