### ISSUE TITLE
Rebranding "Ether-1" as "ETHO Protocol"

### ISSUE THREAD

**Issue by hashratez** [Ether1Project/ECPs#36]
The cryptocurrency space, with the advent of DeFi and new solutions has exploded in the last year and a clear and unique name is critical.  While "Ether-1" has serviced us well, often it has been confused with Ethereum or other "Eth_____" spin-offs projects.  

Rebranding has been discussed openly for several years but the cost has always been an issue.  Recently a proposal was suggested to rebrand as "ETHO Protocol" which is unique and more importantly lets the project keep the ETHO ticket symbol for Wallets & Exchanges.  

The cost of rebranding would be minimal as the greatest expense would be with wallets and exchanges and this is avoided.

The project would keep the Red Diamond Logo as well.

Finally the word "Protocol" itself is very descriptive and indeed represents more of what Ether-1 is all about: a set of rules to conducted business in the digital world.  

The Ether-1 Council has discussed the name change and is in agreement for the rebranding.  We post this here for input from our community.  Let us know what you think!

**Comment by dylie** [comment]
I fully agree with this. 

The ETHO Protocol will stand strong!

-Dylie

**Comment by deslashh** [comment]
This sounds amazing!
More proffesional aswell!

-Deslash

**Comment by pistol22cal** [comment]
I am in agreement

**Comment by Crypto-Saiyan** [comment]
Fully agree on this.

"ETHO Protocol" sounds Powerfull & Professional.
