### ISSUE TITLE
ECP Funding Smart Contract & Dashboard

### ISSUE THREAD

**Issue by hashratez** [Ether1Project/ECPs#4]
If an ECP is approved by the Community it should be accomplished by something similar to the Staking Dashboard.  It would be nice to have a list of ECPs and that status of the funding level, if the ECP is "Open" it has not reached the funding required, if it is "Closed" then it is 100% funded.  It would be very nice to also be able to click on the ECP to "drill down" and see those Community members that have contributed to the ECP funding -- a live list with the Members who contributed the most in order top down.  When the Community Member clicks contribute they have the ability to provide a screen name with the donation.  People can contribute in anonymity or for fun in the name of someone/cause/charity even.

In this case the SC would be a simple list of contributors, names, and amounts.  Not sure about the release of funds etc, I think it should be tied to the multi-sig wallet controlled by the PC.  So each ECP SC would be birthed by the PC multi-sig wallet.  Did I get that correct?  Devs?  LOL.

In accordance with my other proposal, this ECP Funding Dashboard Budget is $100* and I will fund it since there is no dashboard yet for others to contribute.

*Dev-Team I can contribute the ETHO to the Dev Fund etc, let me know if this is OK?  Please advise on the time/cost for the SC Template and Dashboard, just wanted to get started somewhere...  Thanks!

**Comment by pistol22cal** [comment]
ECP-1 will pass and once it does all funds will go to that wallet. ECP's will then be funded by that wallet or outside.
